Algoritmo "DistanciaMetros"

Var
    numero: real


Inicio
      Escreva("Digite uma distância em metros: ")
      leia(numero)
      Escreva("")
      
      escreval ("A distância de ", numero, " corresponde a:")
      escreval (numero/1000, " Km")
      escreval (numero/100, " Hm")
      escreval (numero/10, " Dam")
      escreval (numero*10, " dm")
      escreval (numero*100, " cm")
      escreval (numero*1000, " mm")

      escreval("")

Fimalgoritmo